[project]
name = "e-commerce"
version = "0.1.0"
description = "Educational OOP e-commerce core project"
authors = [
    { name = "alekseimesechko", email = "almsar99@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "mypy (>=1.19.1,<2.0.0)",
    "black (>=24.0.0,<25.0.0)",
    "isort (>=5.13.0,<6.0.0)"
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
python_version = "3.13"
strict = true
warn_unused_ignores = true
disallow_any_generics = true

[tool.black]
line-length = 88
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
